# Database configuration file

development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: astro_development
  username: root
  password: root 
  # socket: /opt/bitnami/mysql/tmp/mysql.sock
  port: 3306
  pool: 200
  wait_timeout: 28800

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: astro_production
  username: root
  password: root 
  # socket: /opt/bitnami/mysql/tmp/mysql.sock
  port: 3306
  pool: 200
  wait_timeout: 28800
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: astro_test
  username: root
  password: root 
  #socket: /opt/bitnami/mysql/tmp/mysql.sock
  port: 3306
  pool: 200
  wait_timeout: 28800
